lib/commons/builder/boundary_data.rb
We may want to include boundaries directories in
boundaries/index.json without having mapped them to an area
type. Previously this would have caused an error.
=> Warn on boundary metadata without :area_type_wikidata_item_id

bin/build
In this case the situation is where a member of an executive has
multiple party memberships at the person level; they might swap around
between builds without this fix.
=> Another fix for predictable ordering of memberships

bin/build, lib/commons/builder/wikidata_queries.rb
Some organizations are used both as executives and legislatures at the
moment, and we're going to merge the JSON objects for them together at
some point. When we do that, we need to preserve which position the seat
count actually refers to, so I've made seat_counts a hash which maps
position item IDs to the seat count.
=> Add a 'seat_counts' attribute to legislatures

lib/commons/builder/wikidata_queries.rb
Consistently having a role_superclass turns out to be useful
downstream, so this commit adds it to the legislative data (it was
already present for executive data).
There is a slightly odd mismatch here, in that the role metadata that
the queries are built from is different between the legislative and
executive directories: for executive, the metadata specifies the
role_superclass, while for legislative it specifies the role.
It would be better if this were consistent, but I think it makes sense
to first get the data included in the build, and then change the
metadata and query generation so they're consistent, checking that the
data produced is the same.
=> Include the role_superclass for legislative positions as well

lib/commons/builder/wikidata_queries.rb
The p:P279/ps:P279* relation wasn't right - if anything it should have
been (p:P279/ps:P279)* but that always seems to time out. wdt:P279*
works, and we don't know of any cases where using wdt: causes problems
so far, so switch both the constraints on role_superclass to use wdt
instead.
In addition, we use a '+' instead of '*' when checking that
?role_superclass is a subclass (at some level) of 'legislator', so that
we don't end up with ?role_superclass just being 'legislator' (which
isn't useful to know, since we know these are legislative positions
already).
=> Use wdt: instead of p:/ps: for finding role_superclass relationships

Gemfile.lock, bin/generate_legislative_index, commons-builder.gemspec, lib/commons/builder/legislative_term.rb, lib/commons/builder/legislature.rb, lib/commons/builder/wikidata.rb, lib/commons/builder/wikidata_queries.rb, test/commons/legislative_index_test.rb, test/fixtures/legislative-index-terms.srj, test/fixtures/legislative-index.srj
An attempt at addressing #10.
Mostly looks to be doing the right thing on Canada, except:
* ~~doesn't find the existing term for the House of Commons (Q21157957), but I think that's because it's attached to the Parliament, not the house.~~ (I think this is happy now)
* ~~two houses (Q1517320, Q2994129) don't make it in because it doesn't find their position item~~ (one data error fixed in wikidata, the other was the result of a more complex model than expected so was a query fix) 
* Montreal's Borough Mayor (Q47450833) is excluded for not being a councillor or legislator. Is this a wrong interpretation? (still not there)
* The Legislative Assembly of British Columbia (Q1323479) is missing. It looks to be modelled as a part of the Parliament of British Columbia (Q6564780), which could …
=> Generate legislative/index.json

bin/build
No tests on this one, because it's in `bin/` and I don't yet know a satisfactory way of testing what's written to stdout.
Closes #31.
=> Emit a warning if a position_item_id in a branch index isn't in boundaries

bin/build, bin/generate_executive_index, bin/generate_legislative_index, lib/commons/builder/config.rb, lib/commons/builder/current_executive.rb, lib/commons/builder/executive.rb, lib/commons/builder/legislative_term.rb, lib/commons/builder/legislature.rb, lib/commons/builder/wikidata.rb, lib/commons/builder/wikidata_labels.rb, lib/commons/builder/wikidata_queries.rb, lib/commons/builder/wikidata_results.rb, test/commons/builder/config_test.rb, test/commons/builder/executive_test.rb, test/commons/builder/wikidata_results_test.rb, test/commons/builder/wikidata_test.rb, test/commons/legislative_index_test.rb, test/fixtures/config/config-with-language-map.json, test/fixtures/config/config.json
This is intended to remove Facebook-specific language codes from our commons
repositories. The mapping to Facebook codes can and should happen further
downstream in the data pipeline.
WiP. This will be split up and possibly tidied before being merged.
General idea:
* Multilingual labels exposed with `wmf:[wikidatalang]` keys, instead of the
previous `lang:[fblang]` keys. The `wmf:` part is supposed to hint at these
being Wikimedia Foundation language codes, but I'm open to alternative
suggestions for what this should look like.
* Config objects now expose languages and country_wikidata_id through
accessors, not by exposing their inner values.
* Config.languages now encapsulates falling back to language_map with a
warning.
* All instances of language_map.values replaced with languages
* …
=> Move to using `languages` (an Array) in place of `language_map`

lib/commons/builder/executive.rb, lib/commons/builder/legislature.rb
This ensures in `Executive.list` and `Legislature.list` that queries are always written to disk before attempting to executive then against the Wikdiata SPARQL endpoint.
Closes #46, as it supports easier debugging of queries that don't return. See that issue for a description of the problem.
Not including tests as this isn't a functional change.
=> Change order of statements to ensure queries saved before running.

lib/commons/builder/wikidata_queries.rb
This change makes the executive index query return far more quickly, resolving the problem with timeouts documented in #45. Hence, this closes #45.
In almost all circumstances — including this one — `FILTER NOT EXISTS` and `MINUS` are functionally equivalent, but `MINUS` is far more performant here. In short, `FILTER NOT EXISTS` will be constructing the bracketed resultset anew for each `?adminArea`, whereas `MINUS` will be constructing it once and minusing those results from previous results.
No tests, as this is non-functional change.
=> s/FILTER NOT EXISTS/MINUS/ in executive index query

.rubocop_todo.yml, Gemfile.lock, commons-builder.gemspec, lib/commons/builder/current_executive.rb, lib/commons/builder/executive.rb, lib/commons/builder/legislative_term.rb, lib/commons/builder/legislature.rb, lib/commons/builder/queries/date_condition.rq.liquid, lib/commons/builder/queries/executive.rq.liquid, lib/commons/builder/queries/executive_index.rq.liquid, lib/commons/builder/queries/label_service.rq.liquid, lib/commons/builder/queries/legislative.rq.liquid, lib/commons/builder/queries/legislative_index.rq.liquid, lib/commons/builder/queries/legislative_index_terms.rq.liquid, lib/commons/builder/queries/select_admin_areas_for_country.rq.liquid, lib/commons/builder/queries/term_condition.rq.liquid, lib/commons/builder/wikidata_queries.rb, test/commons/builder/wikidata_queries_test.rb
This resolves #55, and should make #54 and #50 easier.
=> Split each query out into its own template

bin/build, bin/generate_executive_index, bin/generate_legislative_index, lib/commons/builder/config.rb, lib/commons/builder/current_executive.rb, lib/commons/builder/executive.rb, lib/commons/builder/legislative_term.rb, lib/commons/builder/legislature.rb, lib/commons/builder/queries/select_admin_areas_for_country.rq.liquid, lib/commons/builder/wikidata.rb, lib/commons/builder/wikidata_queries.rb, test/commons/builder/config_test.rb, test/commons/builder/current_executive_test.rb, test/commons/builder/executive_test.rb, test/commons/builder/legislative_term_test.rb, test/commons/builder/wikidata_queries_test.rb, test/commons/builder/wikidata_test.rb, test/commons/legislative_index_test.rb
This will support adding more parameters to the config which can then be used to inform query generation, such as overriding regional administrative area Wikidata type IDs, and population thresholds (as requested in #54).
=> Pass config through query generation methods to templates

lib/commons/builder/queries/label_service.rq.liquid, test/commons/builder/wikidata_queries_test.rb
The regression was introduced in 9fb0986 when `languages` was removed from the context and replaced with `config`, making `languages` available as `config.languages`, without updating `lib/commons/builder/queries/label_service.rq.liquid`.
Added a regression test, but we should also ensure that in general attempting to access variables not in the context should raise an exception.
Closes #59.
=> Fix regression: only 'en' was appearing in label service template output

lib/commons/builder/config.rb, lib/commons/builder/queries/select_admin_areas_for_country.rq.liquid, test/commons/builder/config_test.rb, test/commons/builder/wikidata_queries_test.rb, test/fixtures/config/config-additional-admin-areas.json
This adds:
* Support for an optional `additional_admin_area_ids` key in `config.json`, taking an array.
* An extension to the `select_admin_areas_for_country` query to include an additional UNION clause to return the given areas
* Tests for the changes to `Config`, and to ensure that the template includes the right `VALUES` entries
=> Allow additional admin areas to be specified in config.yaml

lib/commons/builder/queries/executive.rq.liquid, lib/commons/builder/queries/legislative.rq.liquid, test/commons/builder/wikidata_queries_test.rb
Until now, it's been possible for fictional humans (e.g. fictional prime
ministers) to be returned.
Also tested on the UK, resulting in Harriet Jones no longer being included.
Closes #65.
=> Ensure branch person queries always return real people

README.md, lib/commons/builder/config.rb, lib/commons/builder/queries/select_admin_areas_for_country.rq.liquid, test/commons/builder/wikidata_queries_test.rb
This goes half-way to addressing #53, the other half being the ability to override the use of a P17 relationship. It does however allow us to do Costa Rica, where we're interested in cantons, which aren't FLACSen.
=> Allow regional admin area type to be overridden from FLACS

lib/commons/builder/legislative_term.rb, lib/commons/builder/queries/legislative.rq.liquid, test/commons/builder/legislative_term_test.rb
If there's a term-specific position, we should use it to find results, but
should still expose the generic position ID in results, to hide the vagaries of
there being a term-specific position.
This also means that the associated positions in the boundaries index can use
the generic position ID, and won't need updating every time a new term starts
(with its associated position).
Closes #76.
=> Always use legislature position for exposed/serialized role.

bin/build, lib/commons/builder.rb, lib/commons/builder/position_data.rb, lib/commons/builder/queries/information_from_positions.rq.liquid, test/commons/builder/position_data_test.rb, test/fixtures/brazil-position-data.srj
In the downstream build, we need to be able to show for each area the
positions that are associated with it - not just the position item ID
(available from boundaries/build/index.json) but also what level it's at
(national, regional, local), what chamber or organization it's
associated with (e.g. a cabinet, a legislature), and whether it's an
executive or legislative position.
The results of us querying Wikidata for members of these positions will
bring in some of this data (and could be extended to the rest) but that
will only be for areas where we know who the representatives are. That's
not good enough - we should have a complete record of the areas we're
concerned with from the country from the data under boundaries/ and we
need to find this rich position data for each of those.
This …
=> Fetch rich position data for area-associated positions

lib/commons/builder/executive.rb, test/commons/builder/executive_test.rb, test/fixtures/executive-index-two-positions.srj
Previously this would attempt to create a new Executive object per
position and then fail to sort them. This now groups all positions for a
given executive into the same Executive object.
Closes #85.
=> Executive.list> handle one executive having multiple positions

lib/commons/builder/queries/legislative.rq.liquid, lib/commons/builder/queries/legislative_index.rq.liquid
If a house has multiple position 'has part's, and one subclasses
another, then we don't need to include the subclass position in the
legislative index. We can find holders of the subclass position in the
legislative membership query.
This doesn't handle the case of a house having 'has part' positions that
don't subclass each other, which will still cause duplicated entries in
the legislative index, for which we should warn.
No tests as this is just ("just") query changes, which we never satisfactorily test anyway.
Closes #87.
=> Handle legislative positions that subclass other positions we return

lib/commons/builder/legislative_term.rb, lib/commons/builder/legislature.rb, lib/commons/builder/queries/legislative_index_terms.rq.liquid, test/commons/builder/legislative_index_test.rb, test/commons/builder/legislative_term_test.rb, test/fixtures/legislative-index-terms.srj
Adds `number_of_seats` to legislative terms in the legislative index, where they can be deduced.
This will support presenting a % completion metric on commons-explorer, and closes #79.
=> Collect seat counts for legislative terms

lib/commons/builder/membership_data.rb, test/fixtures/membership_data/results.json
Previously, if a membership row was duplicated, we'd end up with a link
item in the person for every row, even if the link was the same. This
calls `.uniq!` on the links to ensure there are no duplicates.
This is tested by adding a duplicate row to the fixtures and checking
that it still produces the expected output data.
=> Deduplicate person links if multiple result rows

lib/commons/builder/queries/legislative.rq.liquid, lib/commons/builder/queries/term_condition.rq.liquid
This extends the term condition subquery to include memberships (P39s) that aren't directly attached to the term with a "parliamentary term" qualifier, but whose start/inception dates overlap the term to some extent.
This helps support legislatures where members are appointed for life but where there is a background parliamentary term system, e.g. in the Canadian Senate and the British House of Lords. Examples:
* https://www.wikidata.org/wiki/Q7416#Q7416$8520BDD5-BC44-456C-AECF-CF841BE78E7C
* https://www.wikidata.org/wiki/Q355188#Q355188$8A400CDA-3F16-4A41-8185-0321CEDEA7C2
See the comment in the term_condition query template for a further explanation of logic encoded in the query.
No tests, as it's a query change against upstream data and we're not good at testing that.
=> Date-aware term condition

lib/commons/builder/queries/executive.rq.liquid, lib/commons/builder/queries/legislative.rq.liquid
Adding ?role_superclass resolves unstable sort orders when a ?role has
more than one superclass, and the others are added for completeness.
=> Add extra vars to membership query sorts for stability.

lib/commons/builder/legislature.rb, test/commons/builder/legislature_test.rb
This is fixing the problem seen at https://github.com/everypolitician/proto-commons-taiwan/pull/31/commits/ba72cd38098344ea04cb06c88c2ab8d8b84d9264#diff-c423aa3204bf24fec2c4cf4394556ae7R20
=> Don't show seat count if there's no position or seat count defined

lib/commons/builder/legislature.rb, lib/commons/builder/queries/legislative_index.rq.liquid, test/commons/builder/legislative_index_test.rb, test/fixtures/missing_position/legislative-index-terms.srj, test/fixtures/missing_position/legislative-index.srj
Two related changes:
* Warn on and don't include legislatures without positions
* Ignore legislatures that have parts that are also legislatures
This means we'll no longer have `"position_item_id": null` in our legislative index, which causes trouble down the line, and we'll be warned of legislatures without positions. We also now exclude legislatures that have legislatures within them — see second commit message for more detail.
=> Sublegislatures edge case

integrity-config.yml
Previously, this checked every CSV under boundaries, which included
those in boundaries/source/, not all of which are guaranteed to be
UTF-8. Any non-UTF-8 source CSV therefore caused the integrity checks to
fail with an exception when parsed.
This does mean that repositories with boundaries not in
boundaries/build/ don't have their CSV files checked, but those are
becoming increasingly rare, and can/should be moved to use
boundaries/build.
=> Only integrity-check WIKIDATA in boundaries/build CSV files

lib/commons/builder/queries/legislative_index.rq.liquid
Queries previously picked up dissolved positions, e.g. https://www.wikidata.org/wiki/Q56876060, which makes it slightly non-deterministic as to which position is used for the files generated on disk.
No tests because purely a query change which we can't test effectively (as before).
=> Ignore dissolved legislative positions

lib/commons/builder/queries/executive_index.rq.liquid, lib/commons/builder/queries/information_from_positions.rq.liquid
This extends previous work with legislative positions to also ignore dissolved positions in executive index and position data queries
Also includes some clause reordering for clarity.
No tests as it's just a query change and we struggle to test those.
Follows on from #110, which only covered the legislative index.
=> Ignore dissolved positions in executive index and position-data

lib/commons/builder/legislative_term.rb, test/commons/builder/legislative_term_test.rb
=> Always expose term dates, even when there is an item ID.

bin/build, lib/commons/builder/membership_data.rb, lib/commons/builder/queries/legislative.rq.liquid, lib/commons/builder/queries/term_condition.rq.liquid, lib/commons/builder/wikidata_results.rb, test/commons/builder/membership_data_test.rb, test/commons/builder/wikidata_results_test.rb
=> Add term ID to memberships if explicitly linked.

lib/commons/builder/queries/term_condition.rq.liquid
If a membership overlaps the term we're querying about through an
explicit start or end date, but it's also linked to another term then we
want to exclude it because it's likely not been updated with an end date
yet.
This is particularly important when querying about future terms, as
current memberships can't yet be given an end date, but it can't be
assumed that the membership also applies to the future term.
No tests as this is just a query change.
=> Exclude memberships that overlap a term, but which are for another term

bin/build
`!str == otherStr` will always be false, regardless of whether or not `str` and `otherStr` are equal, as `!` binds more tightly than `==`, turning the LHS into `false`.
This bug explains why this warning was never effective.
No tests as we (wrongly) don't test `bin/build`.
Resolves #119.
=> Fix the null parent_id check
